[project]
name = "pman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fburleson", email = "joelburleson0104@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "copier>=9.18.2",
    "dulwich>=1.2.15",
    "rich>=15.0.0",
    "typer>=0.27.2",
]

[project.scripts]
pman = "pman.cli.main:cli"

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "conventional-pre-commit>=4.4.0",
    "pre-commit>=4.6.2",
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

[tool.ruff.lint]
extend-select = ["TD"]
ignore = ["TD003"]
